theme: jekyll-theme-chirpy
# 让 Jekyll 输出 _tabs/ 里的页面，并生成 /tabs/xxx/ 路径
collections:
  tabs:
    output: true
    permalink: /tabs/:title/
  projects:            # ← 新增
    output: true
    permalink: /projects/:name/
  handwork:
    output: true
    permalink: /handwork/:title/



plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  
lang: zh-CN
timezone: Asia/Singapore
title: "Yee Hsu (Yi Xu) | Architect & Explorer"
description: >-
  Portfolio of architecture, urban renewal, and socially engaged design. Selected works, ongoing projects (animal rescue), and notes.
theme_mode: light
url: "https://yeexcalibur.github.io"
baseurl: ""
tabs: true
email: yxu11@outlook.com

favicon: assets/img/favicon.png

# Load custom head styles (for warm tone accent)
head:
  custom: /_includes/head/custom.html

